version: '3.8'

networks: 
    laravel:
        driver: bridge

services:
    mysql:
        image: mysql
        container_name: mysql
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: prex
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        networks: 
            - laravel

    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: app
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        networks: 
            - laravel

    nginx:
        image: nginx
        container_name: nginx
        restart: unless-stopped
        ports:
            - "8000:80"
        volumes:
            - ./src:/var/www/app
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel